version: "3"

services:
    client:
        build: client
        container_name: client
        environment:
            - API_URL=/api/v1
        ports:
            - "8080:8080"
        networks:
            - app-network

    server:
        build:
            context: .
            dockerfile: server/Dockerfile
        container_name: server
        env_file:
            - ./server/.env
        environment:
            - PORT=3000
            - BASE_API_URL=api/v1
            - CLIENT_URL=http://localhost:8080
            - USE_PYTHON_ANALYTICS=${USE_PYTHON_ANALYTICS:-false}
            - PYTHON_BIN=${PYTHON_BIN:-python3}
        ports:
            - "3000:3000"
        command: [
                "sh",
                "-c",
                "npm start",
            ] # Default email and password arguments to database seed script - update your admin email and password
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
